services:
    app.admin.apiary:
        class: AppBundle\Admin\ApiaryAdmin
        arguments: [~, AppBundle\Entity\Apiary, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Apiary, label: Apiary }

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Apiary, label: Category }
